apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-configmap2-single-volume
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sample-app
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      containers:
        - name: configmap-container
          image: nginx:1.12
          volumeMounts:
          - name: config-volume
            mountPath: /usr/share/nginx/html
      volumes:
        - name: config-volume
          configMap:
            name: sample-configmap
            items:
            - key: index.html
              path: index.html
