apiVersion: batch/v1beta1
kind: CronJob
metadata:
  namespace: ex2
  name: ex2-job
spec:
  schedule: "*/1 * * * *"
  successfulJobsHistoryLimit: 5
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox
            command:
            - "sh"
            - "-c"
            - exit $((RANDOM % 2))
          restartPolicy: Never
