apiVersion: v1
kind: Pod
metadata:
  name: ex3-pod
  namespace: ex3
spec:
  containers:
  - name: db
    image: mysql
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "password"
    resources:
      requests:
        memory: "1Gi"
        cpu: "1000m"
      limits:
        memory: "2Gi"
        cpu: "2000m"
  - name: wp
    image: wordpress
    resources:
      requests:
        memory: "1Gi"
        cpu: "1000m"
      limits:
        memory: "2Gi"
        cpu: "2000m"
    volumeMounts:
    - mountPath: /wordpress
      name: data
  volumes:
  - name: data
    hostPath:
      path: /tmp/data
      type: DirectoryOrCreate
