apiVersion: v1
kind: Pod
metadata:
  name: ex7-pod
  namespace: ex7
spec:
  initContainers:
    - name: output-1
      image: centos:6
      command: ['sh','-c', 'curl https://adtech.cyberagent.io/ > /usr/share/nginx/html/index.html']
      volumeMounts:
      - name: html-volume
        mountPath: /usr/share/nginx/html/
  containers:
    - name: nginx-container
      image: nginx:1.12
      volumeMounts:
      - name: html-volume
        mountPath: /usr/share/nginx/html/
  volumes:
  - name: html-volume
    emptyDir: {}
